### ISSUE TITLE
Lowervalue & Uppervalue -> thumb wrong position

### ISSUE THREAD

**Issue by willowvil** [halkar/xamarin-range-slider#38] opened 2016-12-14 23:20 UTC
When setting lowervalue and uppervalue, thumb position is not correct

```
var slider = new RangeSlider()
            {
                HorizontalOptions = LayoutOptions.FillAndExpand,
                BarHeight = 6,
                ShowTextAboveThumbs = true,
                MinimumValue = 0,
                MaximumValue = 10,
                StepValue = 1,
                LowerValue = 0,
                UpperValue = 5
            };
```

![sin titulo](https://cloud.githubusercontent.com/assets/19213951/21205338/fa58c194-c25b-11e6-8721-ab3f726ca38c.png)

**Comment by halkar** [comment] 2016-12-17 22:42
Fixed in v0.6.9.

**Comment by willowvil** [comment] 2016-12-19 08:01
Hi @halkar thanks for fixing this. I have found a little bug. When declaring the RangeSlider, I set an UpperValue, however the thumb position is not correct. After the control has been declared, setting UpperValue works correctly.

Thanks!

**Comment by halkar** [comment] 2016-12-19 08:52
@willowvil what do you mean by "When declaring" and "After the control has been declared"? Can you provide some source code?

**Comment by willowvil** [comment] 2016-12-19 09:29
Sorry! Better with an example:

```
var _slider = new RangeSlider()
            {
                BarHeight = 6,
                ShowTextAboveThumbs = true,
                StepValueContinuously = false,
                StepValue = 1,
                MinimumValue = 0,
                MaximumValue = 10,
                LowerValue = 0,
                UpperValue = 6
            };
```
Result:
![uno](https://cloud.githubusercontent.com/assets/19213951/21307433/c3ccc120-c5d5-11e6-8fc2-ac702130f616.png)

Then, I change UpperValue with a button and then it works great:

![dos](https://cloud.githubusercontent.com/assets/19213951/21307483/f39f39a0-c5d5-11e6-94ff-6b17495c75d5.png)

**Comment by halkar** [comment] 2016-12-19 10:17
@willowvil I can't reproduce the issue on the latest version (v0.6.9).

**Comment by willowvil** [comment] 2016-12-19 10:31
Ok. I have reinstalled (v0.6.9), cleaned my project and rebuilt it. Now is working. Sorry ;) and thanks!!

**Closed** 2016-12-19 10:32 UTC
Labels: bug
