### ISSUE TITLE
Does not work properly in IOS master detail page

### ISSUE THREAD

**Issue by michelmoorlag** [halkar/xamarin-range-slider#60] opened 2017-03-28 07:12 UTC
Issue 1.
The control is really nice but I have some issues. On android if you put this control in the detail of a master detail page it works all fine. This is because you have to slide open the menu from the left side. On IOS however you can slide open the master menu from any place in the screen by swiping to the right. So if you swipe the slider to the right it will move a small portion. Then it locks and the menu starts appearing and moving to the right. It seems that the swiping gesture of the menu has preference above the swiping on your control and this is wrong. With a normal slider in the detail it does work fine though.
Issue 2.
I need one slider but I want the number above the slider. So I show the number above and hide the min thumb. The min thumb is hidden but the number above it is still visible in IOS. I would expect that if you hide a thumb the number above it is hidden too.

**Comment by halkar** [comment] 2017-03-28 08:10
@michelmoorlag 
1. For the first issue I can only recommend setting `IsGestureEnabled` to `false`.
https://github.com/halkar/xamarin-range-slider/issues/48#issuecomment-277507653
I will try to fix it but can't guarantee any positive results.
2. Thanks! I'll fix it ASAP.

**Comment by michelmoorlag** [comment] 2017-03-30 12:39
@halkar 
To reproduce issue 1 just create a basic XF master detail page and put the range slider in a detail page.
I could disable the IsGestureEnabled on the master but I really like this feature.  So if you can make this work within a master detail configuration you will be my best friend ... ever :)

**Comment by halkar** [comment] 2017-04-03 10:21
Both fixed in 0.6.16

**Closed by halkar** 2017-04-03 10:21 UTC
Labels: bug

**Comment by LiquidFenrir** [comment] 2020-05-04 19:05
Hello, I think there has been a regression, at least on Android 7.1.1.
Putting a `RangeSlider` in the `Master` (sidebar) page of a `MasterDetailPage` makes the slider unusable, touching either of the thumbs closes the sidebar, and puts the thumb you were touching to the maximum value.
I think, from testing, that it's because of setting `IsGestureEnabled` to `false`. You can make an auto closing sidebar by adding a `IsPresentedChanged` handler to the `MasterDetailPage` that toggles the `IsGestureEnabled`.
I have no idea how to fix this or if fixing it would break other versions, but for now I'm stuck while writing an app because of this :/
