### ISSUE TITLE
Android : LowerValue binding not correct

### ISSUE THREAD

**Issue by slam023** [halkar/xamarin-range-slider#79] opened 2017-08-08 03:40 UTC
I tried to bind the values to the lower value and the upper value but the lower value is not shown the right value. My model have 5 as lower value but the range slider will display 4. The upper value seems fine though.

**Comment by halkar** [comment] 2017-08-08 03:42
@slam023 do you have a sample project to reproduce the issue?

**Comment by slam023** [comment] 2017-08-08 11:45
I changed the code so don't have the sample code to show you. 

The configuration I have for the slider: 

Minimum value = 0 and Maximum value = 20.  LowerValue and UpperValue is bound with my properties. The step values is 0 and not continuous.

**Comment by halkar** [comment] 2017-08-08 12:26
Thanks @slam023 I'll have a look.

**Comment by halkar** [comment] 2017-08-13 07:33
@slam023 I can't reproduce the issue. Can you check https://github.com/halkar/xamarin-range-slider/compare/feature/mvvm-test ?

**Comment by halkar** [comment] 2017-09-30 08:52
fixed in 0.7.4

**Closed by halkar** 2017-09-30 08:52 UTC
Labels: bug
